### ISSUE TITLE
build fails on mac os x 10.6, but simple to fix

### ISSUE THREAD

**Issue by gschueler** [spoutn1k/mcmap#1]
draw.cpp: In function ‘bool createBitmap(FILE*, size_t, size_t, bool)’:
draw.cpp:86: error: ‘fseeko64’ was not declared in this scope

just replace all "fseek064" in draw.cpp with "fseek" and it works fine

just need to find appropriate #ifdef...

**Comment by Zahl** [comment]
Hi, thanks for the feedback, I'll try to add a proper directive to deal with that.
Can you tell me which gcc version you're using? I'm trying to figure out if this has to do with an old gcc version or just the gcc for OS X.

**Comment by gschueler** [comment]
gcc --version
i686-apple-darwin10-gcc-4.2.1 (GCC) 4.2.1 (Apple Inc. build 5646)

I think that os x 10.6 is all 64-bit and so doesn't have specific 64 bit versions of those functions

**Comment by gschueler** [comment]
closing
