### ISSUE TITLE
GUI out of date

### ISSUE THREAD

**Issue by pedter** [spoutn1k/mcmap#102]
Compiling myself for Windows is above my head but it appears that issues still in the latest GUI version have already been corrected for 1.20.1 (#94/#95/#96/#97/#98) and 1.20.4 (#101) in the source. Is it at all acceptable to request a fresh Windows compile be pushed to releases? I'll attach the errors I'm seeing below (in the v3.0.2 GUI release for 1.19) just in case they don't match and more info is needed. Thanks!

```
[debug] Parsing C:/Users/default/AppData/Roaming/.minecraft/saves/lumina\level.dat
[info] Scanning C:/Users/default/AppData/Roaming/.minecraft/saves/lumina\region
[debug] World spans from -512.-432.-64.511.511.319.North-West
[debug] Rendering test with -512.-432.-64.511.511.319.North-West
[debug] Memory capacity: 72 fragments - 1 fragments scheduled
[debug] Rendering -512.-432.-64.511.511.319.North-West
[debug] Rendered in 841ms
[debug] Canvas canvas (0x0 for 2147483647.2147483647.32767.-2147483648.-2147483648.-32768.North-West)
 - Void canvas, offset 0.0
[error] Canvas is empty !
```

**Comment by spoutn1k** [comment]
Yeah I need to do that sorry, I changed machines and lost the original windows environment I used to compile the binary. I need to sit down and recreate it but working with windows is always such a fun time I haven't gotten around to do that. Expect it next week.

**Comment by spoutn1k** [comment]
Done ! Please reopen this if you have any issues.
