### ISSUE TITLE
No license information attached to source code

### ISSUE THREAD

**Issue by ghost** [spoutn1k/mcmap#11]
This is a great app and I'd like to build a GTK+-based GUI for use on Debian/Ubuntu and other Gnome-based Linux distros, however I have not been able to locate any information about what license under which this code is available.

**Comment by Zahl** [comment]
Ya, have successfully been procrastinating that. Will probably use 2BSD and do a commit soon.

**Comment by ghost** [comment]
Cool :)

**Comment by Zahl** [comment]
Oh and ignore the commit's comment saying its CC-BY-SA... Didn't make up my mind there yet ;)
