### ISSUE TITLE
std::bad_alloc

### ISSUE THREAD

**Issue by flps42** [spoutn1k/mcmap#13]
Maybe this is on my end. I'm new to compiling source on linux. It compiles fine but when I run it I get the following output...

mcmap 2.1
McRegion world format detected.
Scanning world...
Min: (-166|-121) Max: (225|255)
Image dimensions are 18954x8570, 32bpp, 619.64MiB
Pass 1 of 4...
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Terrain takes up 1169.69MiBAborted

**Comment by flps42** [comment]
Figured it out sorry to bug you with this.

**Comment by dldx** [comment]
For googlers: I fixed it by freeing up more memory as my laptop didn't have enough to render the map.
