### ISSUE TITLE
My large world map is throwing an error

### ISSUE THREAD

**Issue by jmurth1234** [spoutn1k/mcmap#16]
I'm trying to run mcmap on my Ubuntu 11.04 32-bit vps server. I have a large map, and it throws an error when renderingd
The error is shown below:

root@server:~/mcmap# ./mcmap /root/Minecraft/world/
mcmap 2.2 by Zahl
McRegion world format detected.
Scanning world...
Min: (-199|-239) Max: (198|262)
Image dimensions are 17994x9258, 32bpp, 635.48MiB
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted

The map size is a 3000 block radius circular map.

**Comment by jmurth1234** [comment]
nvm seems my vps hasn't got the ram :(

**Comment by Zahl** [comment]
Check the help output, there's a way to limit the mem usage ;)
Just run ./mcmap with no parameters to see all the available options.
