### ISSUE TITLE
Support Anvil file format

### ISSUE THREAD

**Issue by ironiridis** [spoutn1k/mcmap#17]
Minecraft 1.2.2 (released today) now converts McRegion format region data to Anvil format. mcmap does not appear to recognize or process this new format at all.

**Comment by Zahl** [comment]
Yes it does, see latest commit.

**Comment by ironiridis** [comment]
Hah! Sorry, the tab I had loaded with mcmap hadn't been reloaded in the 5 minutes it took me to commit that issue. Thanks. :)

**Comment by Zahl** [comment]
Didn't test it too much yet though, that's why it's not posted on minecraftforums yet.

**Comment by ironiridis** [comment]
It's generating a blank image on my server, just FYI.

**Comment by Zahl** [comment]
How about now? Found one little bug I just squashed.

Otherwise, are you using any fancy options? Cave mode isn't supported for example for Anvil.
-night and -skylight should work.
Also I didn't process any huge worlds yet, just some single player maps. Have to sleep now. ;)

**Comment by ironiridis** [comment]
Just tested it, much better! An 18M PNG file as a result. (Working via SSH at the moment.)
