### ISSUE TITLE
Cave mode issues

### ISSUE THREAD

**Issue by orphu** [spoutn1k/mcmap#19]
The recent push fixed cave mode mostly, but for some reason cave mode seems to find different caves than blendcave mode. Blendcave seems to work better, and is more like cave mode used to be. I've not spent much time looking into it yet. 

Example:

http://mc.bubblemod.org/maps.php

**Comment by Zahl** [comment]
Should be fixed now, please check out the latest version.

**Comment by orphu** [comment]
Fixed!
