### ISSUE TITLE
-marker broken since 1.2

### ISSUE THREAD

**Issue by M3t0r** [spoutn1k/mcmap#21]
i dont know for sure if it was since 1.2 or some time before 1.2, but adding `-marker r 0 0` won't add any marker at all.

i tested this with several maps on several machines (self compiled on mac 10.6, 10.7 and debian 4)

is this just overlooked or a serious change with the new map-format?

**Comment by 404d** [comment]
I've been struggling with markers at least since 1.1, not being able to add anything 1 chunk away from spawn. I can verify that it doesn't work at all with a clean checkout of c3360f0257 self compiled on OS X 10.7.2. Any idea what's the problem?

**Comment by Zahl** [comment]
Found the issue; will be fixed in the next days hopefully.
