### ISSUE TITLE
Would you consider adding a README.md file?

### ISSUE THREAD

**Issue by dooguls** [spoutn1k/mcmap#29]
In Github parlance, adding this file to your repository will cause the readme to be automatically displayed in the Github web gui. If you're willing to consider it, would you further be willing to add a couple suggestions to those compiling the code for ubuntu? Something like:

---
## Ubuntu

Compiles just fine up to Ubuntu 13.04 but you might need to apt get a couple packages if you don't have them already.
-  sudo apt-get install build-essential
-  sudo apt-get install zlib1g-dev
-  sudo apt-get install libpng12-dev
  Then of course 'make' in the source code directory and you should be good to go.

---
## Couple run time suggestions

If you have low amounts of RAM on your box, the program will rightly complain. I found that -mem 300 worked on my machine and rendered well. 

Thanks for your consideration of this addition.
--dooguls

**Comment by Robert-Cunningham** [comment]
I'll write this up.
