### ISSUE TITLE
make fails on mac snowleopard

### ISSUE THREAD

**Issue by val99erie** [spoutn1k/mcmap#5]
Hi,

I just pulled your latest code changes and tried to build, but I got this error:

mcmap $ make
g++ -O3 -c -Wall -fomit-frame-pointer -pedantic -DWITHPNG -I/usr/local/include main.cpp -o main.default.o
main.cpp: In function ‘int main(int, char*_)’:
main.cpp:374: error: ‘mkdir’ was not declared in this scope
make: *_\* [main.default.o] Error 1

**Comment by PeterN** [comment]
This is the same as issue 6.

**Comment by devyn** [comment]
Yeah, it's been fixed now.

**Comment by Zahl** [comment]
Sorry for that one, was working on Windows then. ;-)
