### ISSUE TITLE
Compilation problem.

### ISSUE THREAD

**Issue by NilsNews** [spoutn1k/mcmap#58]
```
make -C scripts json2bson
g++ -O3 -c -std=c++17 -Wall -I../src/include json2bson.cpp -o json2bson.default.o
json2bson.cpp:1:10: fatal error: filesystem: Datei oder Verzeichnis nicht gefunden
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
Makefile:26: recipe for target 'json2bson.default.o' failed
make[2]: *** [json2bson.default.o] Error 1
Makefile:55: recipe for target 'src/colors.bson' failed
make[1]: *** [src/colors.bson] Error 2
Makefile:50: recipe for target 'all' failed
make: *** [all] Error 2
```

If I want the code compilation.
Always comes this error.

Why?

Thanks in advance.

**Comment by spoutn1k** [comment]
Hey ! Can you give the output of `g++ --version` ? I fear your compiler might be outdated for mcmap.

**Comment by NilsNews** [comment]
> Hey ! Can you give the output of `g++ --version` ? I fear your compiler might be outdated for mcmap.

g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by spoutn1k** [comment]
Unfortunately, it is outdated. [The supported versions are from 8.0 onwards.](https://github.com/spoutn1k/mcmap#compilation-fails) To fix this, use `apt update && apt install g++-10`, to refresh the packages and install `g++10`. Afterwards, you can use the following to compile `mcmap`:
```
CXX=g++-10 make
```

**Comment by spoutn1k** [comment]
Hope this has been fixed. As it is a common problem and fixable, I'll close it.
