### ISSUE TITLE
Old Gui Viewer Windows source files

### ISSUE THREAD

**Issue by ghost** [spoutn1k/mcmap#61]
"Native Windows is currently unsupported, but the program works using Ubuntu on windows to get a linux terminal and launch it from there, as on a linux platform......If anyone has the sources to that old viewer, sharing them to update them would be greatly appreciated."

I found the source files for the old windows mcmap gui. Is it possible to update them?
https://www.dropbox.com/s/piyciwo0vas039f/mcmap-src.zip?dl=0

**Comment by spoutn1k** [comment]
Is this christmas ? I contacted the guy who made this a few months back and even he did not have it anymore.

Let me take a look. In the meantime, thanks for digging this up.

**Comment by spoutn1k** [comment]
After looking at that, I made a GUI using Qt, as it makes the code:
- 100% C++;
- Compatible on Windows, Mac AND Linux, cause I would stop the project if I had to endure visual's studio BS.

If you are interested, you can try and compile the code in windows. You'll need to compile zlib, png and install Qt, but the code itself should work. I will make binaries at some point but once the GUI is more fleshed out.

**Comment by spoutn1k** [comment]
I just posted an archive with a compiled windows interface in [this discussion](https://github.com/spoutn1k/mcmap/discussions/63), please try it and let me know how it went !
