### ISSUE TITLE
Error [LINUX]

### ISSUE THREAD

**Issue by Julius-Babies** [spoutn1k/mcmap#65]
Hi, I've tried to compile mcmap, but there's an error: `mcmap/src/graphical/mcmap-gui_autogen/include/./ui_mainwindow.h:138:40: error: ‘MarkdownText’ is not a member of ‘Qt’
  138 |         outputLabel->setTextFormat(Qt::MarkdownText);` Can you fix that plz?

**Comment by spoutn1k** [comment]
Hey, this sounds like a `mcmap-gui` error. Can you find the version of Qt you have ? You can get it using:

```
qtdiag | head -n 2
```

I'll try and fix this. In the meantime, try `make mcmap`. This should compile the CLI version that is more tested and stable.

**Comment by spoutn1k** [comment]
I wanted to remove Markdown support to increase compatibility - but I left a piece of code with it. The latest commits should fix this. Go ahead and clone `NBT19133`, the error should disappear.

**Comment by Julius-Babies** [comment]
Hi, sorry, I didn't have time in the last week, so here's my output:
vkDebug: Loader Message: 0: setupLoaderTermPhysDevs:  Failed to detect any valid GPUs in the current config
vkDebug: Loader Message: 0: setupLoaderTrampPhysDevs:  Failed during dispatch call of 'vkEnumeratePhysicalDevices' to lower layers or loader to get count.
QVulkanWindow: Failed to get physical device count: -3
Qt 5.12.8 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 9.3.0) on "xcb" 
OS: Ubuntu 20.04.2 LTS [linux version 5.4.0-67-generic]

**Comment by spoutn1k** [comment]
How do you run `mcmap` ? What is your OS ?

**Comment by Julius-Babies** [comment]
My OS is Ubuntu 20.04.2 LTS

**Comment by Julius-Babies** [comment]
I just installed it again, now it works fine :)
