### ISSUE TITLE
Question: about bedrock edition

### ISSUE THREAD

**Issue by DLazaridisGM** [spoutn1k/mcmap#85]
any thoughts about having an option to import worlds from bedrock edition?

**Comment by spoutn1k** [comment]
Hey ! I have thought about it, but I used to play Java and never used BE so I do not have test maps to try.

According to the minecraft wiki, there are a few differences in the way chunks are stored, but the backend is written in C++ and should be easy to merge in the project.

**Comment by DLazaridisGM** [comment]
intresting... thank you for you answer thats enough for me i would offer something but i wouldn't say im much of help      i dont know if i should close this or what so ill leave it up to you

**Comment by spoutn1k** [comment]
I'll close this as it is not really an issue, but do create a discussion ! If more people are interested it'll be a good way to share tips when someone eventually gets to implement it !
